env:
  browser: true
  es6: true
  'jest/globals': true
extends:
  - airbnb
  - 'plugin:jest/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'
  - 'prettier/@typescript-eslint'
  - 'plugin:prettier/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2020
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - prettier
  - jest
settings:
  'import/resolver':
    typescript: {}
  react:
    version: detect
rules:
  'no-use-before-define': off
  '@typescript-eslint/no-use-before-define': warn
  'react/jsx-filename-extension':
    - error
    - extensions: ['.js', '.jsx', '.ts', '.tsx']
  'import/extensions': off
  'react/jsx-one-expression-per-line': off
  'comma-dangle':
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: never
